name: 'Manual: sunxi-nanopi-r1-scarthgap'

on:
  workflow_dispatch:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-sunxi-nanopi-r1-scarthgap:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/sunxi-nanopi-r1-scarthgap.yaml:.github/configs/shared-vols.yaml
      name: sunxi-nanopi-r1-scarthgap
    secrets: inherit
