name: 'Manual: sunxi-orange-pi-r1-kirkstone'

on:
  workflow_dispatch:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-sunxi-orange-pi-r1-kirkstone:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/sunxi-orange-pi-r1-kirkstone.yaml:.github/configs/shared-vols.yaml
      name: sunxi-orange-pi-r1-kirkstone
    secrets: inherit
