name: "MAN: sunxi-orange-pi-3lts-scarthgap"

on:
  workflow_dispatch:

jobs:

  build-sunxi-orange-pi-3lts-scarthgap:
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: .github/configs/release/sunxi-orange-pi-3lts-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: sunxi-orange-pi-3lts-scarthgap
      build_target: pantavisor-starter
      output: pantavisor-starter*.rootfs.wic*
    secrets: inherit