name: 'Manual: imx8qxp-b0-mek-kirkstone'

on:
  workflow_dispatch:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-imx8qxp-b0-mek-kirkstone:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/imx8qxp-b0-mek-kirkstone.yaml:.github/configs/shared-vols.yaml
      name: imx8qxp-b0-mek-kirkstone
    secrets: inherit
