name: 'Manual: colibri-imx6ull-kirkstone'

on:
  workflow_dispatch:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-colibri-imx6ull-kirkstone:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/colibri-imx6ull-kirkstone.yaml:.github/configs/shared-vols.yaml
      name: colibri-imx6ull-kirkstone
    secrets: inherit
