name: "MAN: radxa-rock5a-scarthgap"

on:
  workflow_dispatch:

jobs:

  build-radxa-rock5a-scarthgap:
    uses: ./.github/workflows/buildkas-starter.yaml
    with:
      configs: .github/configs/release/radxa-rock5a-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: radxa-rock5a-scarthgap
    secrets: inherit