name: "MAN: raspberrypi-armv8-scarthgap"

on:
  workflow_dispatch:

jobs:

  build-raspberrypi-armv8-scarthgap:
    uses: ./.github/workflows/buildkas-starter.yaml
    with:
      configs: .github/configs/release/raspberrypi-armv8-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: raspberrypi-armv8-scarthgap
    secrets: inherit