name: 'On Push: raspberrypi-armv8-kirkstone'

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-raspberrypi-armv8-kirkstone:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/raspberrypi-armv8-kirkstone.yaml:.github/configs/shared-vols.yaml
      name: raspberrypi-armv8-kirkstone
    secrets: inherit
