name: 'On Push: sunxi-nanopi-r1-kirkstone'

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-sunxi-nanopi-r1-kirkstone:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/sunxi-nanopi-r1-kirkstone.yaml:.github/configs/shared-vols.yaml
      name: sunxi-nanopi-r1-kirkstone
    secrets: inherit
