name: 'Build Components - scarthgap - musl'

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-raspberrypi-armv8-scarthgap-musl:
    uses: ./.github/workflows/buildkas-components-matrix.yaml
    with:
      configs: .github/configs/release/raspberrypi-armv8-scarthgap.yaml:.github/configs/shared-vols.yaml
      name: raspberrypi-armv8-scarthgap
    secrets: inherit
