name: "PUSH: sunxi-bananapi-m2-berry-scarthgap"

on:
  push:
    paths:
      - '**'
      - '.github/configs/release/**'
      - '!.github/scripts/**'
      - '!.github/templates/**'
    tags-ignore:
      - '**'

jobs:

  build-sunxi-bananapi-m2-berry-scarthgap:
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: .github/configs/release/sunxi-bananapi-m2-berry-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: sunxi-bananapi-m2-berry-scarthgap
      build_target: pantavisor-starter
      output: pantavisor-starter*.rootfs.wic*
      sdk: 1
    secrets: inherit
