name: "Scheduled Recipe Updates"

permissions:
  contents: write
  pull-requests: write

on:
  push:      # <--- Add this temporarily
    branches: [ ci/components-check ]
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Update Script
        run: .github/scripts/check-updates.sh

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.META_PANTAVISOR_UPDATE_COMPONENTS_PAT || github.token }}
        run: |
          git config user.email "pantavisor-meta@ci.pantavisor.io"
          git config user.name "Pantavisor Meta Layer CI"
          
          # Create a new branch for the PR
          BRANCH_NAME="auto-update/components-$(date +%Y%m%d%H%M)"
          git checkout -b "$BRANCH_NAME"
          
          # Stage all modified recipes
          git add recipes-pv/
          
          # Only commit and push if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "recipes-pv: automated srcrev update"
            git push origin "$BRANCH_NAME"
            # Wait a few seconds for GitHub to index the branch
            sleep 5
            gh pr create --title "AutoPR: Automated Upstream Component Updates" \
                         --body "This is a scheduled automated update to sync internal components." \
                         --base master \
                         --head "$BRANCH_NAME" || true
          else
            echo "No changes to commit."
          fi
