
name: "TAG: docker-x86_64-scarthgap"

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '.github/workflows/!WORKFLOW.yaml'
      - '!.github/scripts/**'
      - '!.github/templates/**'
    tags:
      - 0*
      - '*-rc*'
jobs:

  build-docker-x86_64-scarthgap:
    uses: ./.github/workflows/buildkas-upload.yaml
    with:
      configs: .github/configs/release/docker-x86_64-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: docker-x86_64-scarthgap
      build_target: pantavisor-appengine-distro
      output: pantavisor-appengine-distro-*.tar.gz
      sdk: 0
    secrets: inherit
