
name: "TAG: raspberrypi-armv8-scarthgap"

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '.github/workflows/!WORKFLOW.yaml'
      - '!.github/scripts/**'
      - '!.github/templates/**'
    tags:
      - 0*
      - '*-rc*'
jobs:

  build-raspberrypi-armv8-scarthgap:
    uses: ./.github/workflows/buildkas-upload.yaml
    with:
      configs: .github/configs/release/raspberrypi-armv8-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: raspberrypi-armv8-scarthgap
      build_target: pantavisor-starter
      output: pantavisor-starter*.rootfs.wic*
      sdk: 1
    secrets: inherit
