
name: "TAG: colibri-imx6ull-scarthgap"

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '.github/workflows/tag-scarthgap-colibri-imx6ull.yaml'
      - '!.github/scripts/**'
      - '!.github/workflows/**'
      - '!.github/templates/**'
    tags:
      - 0*
      - '*-rc*'
jobs:

  build-colibri-imx6ull-scarthgap:
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: .github/configs/release/colibri-imx6ull-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: colibri-imx6ull-scarthgap
      build_target: pantavisor-starter
      output:  pantavisor-starter*.rootfs.wic* *pv_teziimg.tar.xz pantavisor-README.md
    secrets: inherit
