
name: "TAG: imx8qxp-b0-mek-scarthgap"

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '.github/workflows/!WORKFLOW.yaml'
      - '!.github/scripts/**'
      - '!.github/templates/**'
    tags:
      - 0*
      - '*-rc*'
jobs:

  build-imx8qxp-b0-mek-scarthgap:
    uses: ./.github/workflows/buildkas-upload.yaml
    with:
      configs: .github/configs/release/imx8qxp-b0-mek-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: imx8qxp-b0-mek-scarthgap
      build_target: pantavisor-starter
      output: pantavisor-starter*.rootfs.wic*
      sdk: 0
    secrets: inherit
