
name: "test: raspberrypi-armv8-scarthgap"

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/templates/**'
    tags:
      - test*
jobs:

  build-raspberrypi-armv8-scarthgap:
    uses: ./.github/workflows/buildkas-starter-upload.yaml
    with:
      configs: .github/configs/release/raspberrypi-armv8-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: raspberrypi-armv8-scarthgap
    secrets: inherit